name: Build Pif Matrix

on:
  workflow_dispatch:
  schedule:
    - cron: "37 13 7 * *" # At 13:37 on day-of-month 7. (UTC)

jobs:
  onSchedule:
    name: On Schedule
    strategy:
      matrix:
        device_name: [sailfish, marlin, sunfish, coral, flame, bramble, redfin, husky, shiba, cheetah, raven]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Clone Repo getProps
        uses: whyakari/github-repo-action@v3.1
        with:
          owner: 'whyakari'
          repository: 'getProps'

      - name: Install dos2unix python3 python3-pip
        uses: daaku/gh-action-apt-install@v4
        with:
          packages: dos2unix python3 python3-pip

      - name: Install protobuf and pyrogram, tgcrypto
        working-directory: ./getProps
        run: |
          pip install --upgrade pip
          pip install tgcrypto pyrogram
          pip3 install -Iv protobuf==3.20.3

      - name: Make executable all script
        working-directory: ./getProps
        run: chmod +x *.sh

      - name: Download last ota ${{ matrix.device_name }}
        working-directory: ./getProps
        run: |
          ./last_ota_build.sh ${{ matrix.device_name }}

      - name: Extract Image and build prop ${{ matrix.device_name }}
        working-directory: ./getProps
        run: |
          ./extract_images.sh

      - name: Read final_name from file
        id: read_name
        run: | 
          echo ::set-output name=final_name::$(cat build.txt)
        working-directory: ${{ github.workspace }}

      - name: Copy prop to result ${{ matrix.device_name }}
        working-directory: ./getProps
        run: |
          cp ./**/**/{system,module}.prop .
          mv system.prop build.prop

      - name: Move Build.prop to result
        working-directory: ./getProps
        run: |
          ls
          # mv build.prop result/

      - name: Create Pif ${{ matrix.device_name }}
        working-directory: ./getProps
        run: |
          ./gen_custom_pif.sh json build.prop

      - name: Upload Prop ${{ matrix.device_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.read_name.outputs.final_name }}
          path: result
          if-no-files-found: error
