name: Build Pif Matrix

on:
  workflow_dispatch:
  schedule:
    - cron: "37 13 7 * *" # At 13:37 on day-of-month 7. (UTC)

jobs:
  onSchedule:
    name: On Schedule
    strategy:
      matrix:
        device_name: [sailfish, marlin, sunfish, coral, flame, bramble, redfin, husky, shiba, cheetah, raven]

    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install dos2unix python3 python3-pip
        working-directory: ./getProps
        run: |
          pacman -Syu --noconfirm
          pacman -Sy sh --noconfirm
          pacman -Sy --noconfirm dos2unix python python-pip p7zip wget

      - name: Install protobuf
        working-directory: ./getProps
        run: |
          pip install --upgrade pip --break-system-packages
          pip3 install -Iv protobuf==3.20.3 --break-system-packages

      - name: Make executable all script
        working-directory: ./getProps
        run: chmod +x *.sh

      - name: Download last ota ${{ matrix.device_name }}
        working-directory: ./getProps
        run: |
          ./last_ota_build.sh ${{ matrix.device_name }}

      - name: Extract Image and build prop ${{ matrix.device_name }}
        working-directory: ./getProps
        run: |
          ./extract_images.sh

      - name: Read final_name from file
        id: read_name
        run: | 
          echo ::set-output name=final_name::$(cat build.txt)
        working-directory: ${{ github.workspace }}

      - name: Copy prop to result ${{ matrix.device_name }}
        working-directory: ./getProps
        run: |
          cp ./**/**/{system,module}.prop .
          cp system.prop build.prop

      - name: Move Build.prop to result
        working-directory: ./getProps
        run: |
          mv build.prop result/

      - name: Create Pif ${{ matrix.device_name }}
        working-directory: ./getProps
        run: |
          sh ./gen_custom_pif.sh json result/build.prop

      - name: Upload Prop ${{ matrix.device_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.read_name.outputs.final_name }}
          path: result
          if-no-files-found: error
