name: Build Pif Matrix

on:
  workflow_dispatch:
  schedule:
    - cron: "37 13 7 * *" # At 13:37 on day-of-month 7. (UTC)

jobs:
  onSchedule:
    name: On Schedule
    strategy:
      matrix:
        device_name: [sailfish, marlin, sunfish, coral, flame, bramble, redfin, husky, shiba, cheetah, raven]

    runs-on: ubuntu-latest
    container:
      image: archlinux/base:latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install dos2unix python3 python3-pip
        run: pacman -Sy --noconfirm dos2unix python python-pip

      - name: Install protobuf
        run: |
          pip install --upgrade pip
          pip3 install -Iv protobuf==3.20.3

      - name: Make executable all script
        run: chmod +x *.sh

      - name: Download last ota ${{ matrix.device_name }}
        run: ./last_ota_build.sh ${{ matrix.device_name }}

      - name: Extract Image and build prop ${{ matrix.device_name }}
        run: ./extract_images.sh

      - name: Read final_name from file
        id: read_name
        run: | 
          echo ::set-output name=final_name::$(cat build.txt)
        working-directory: ${{ github.workspace }}

      - name: Copy prop to result ${{ matrix.device_name }}
        run: |
          cp ./**/**/{system,module}.prop .
          cp system.prop build.prop
          mv build.prop result/
          sh ./gen_custom_pif.sh json build.prop

      - name: Create Pif ${{ matrix.device_name }}
        run: |
          sh ./gen_custom_pif.sh json build.prop

      - name: Upload Prop ${{ matrix.device_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.read_name.outputs.final_name }}
          path: result
          if-no-files-found: error
